name: toolkit-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - openssl
  - sqlite
  - vc
  - click
  - openpyxl
  - lxml
  - pyreadline3
  - chardet
  - pywin32
  - six
  - pillow
  - pip:
      - pytest
      - pylint
      - PySide6
      - pywinpty
      - pyte
      - psutil
      - qrcode
      - opencv-python
